// <auto-generated />
using System;
using DoAnCoSo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCoSo.Migrations
{
    [DbContext(typeof(QuanLyThueXeContext))]
    partial class QuanLyThueXeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCoSo.Models.ChucVu", b =>
                {
                    b.Property<int>("ID_ChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ChucVu"));

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Name_ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_ChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DatLichThueXe", b =>
                {
                    b.Property<int>("ID_DatLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DatLich"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BienSoXe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_DatLich", "Email", "BienSoXe");

                    b.HasIndex("BienSoXe");

                    b.HasIndex("Email");

                    b.ToTable("datLichThueXes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DiaDiem", b =>
                {
                    b.Property<int>("ID_DiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DiaDiem"));

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Name_DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DiaDiem");

                    b.ToTable("diaDiems");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HangXe", b =>
                {
                    b.Property<int>("ID_HangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HangXe"));

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Name_HangXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_HangXe");

                    b.ToTable("hangXes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HinhAnhXe", b =>
                {
                    b.Property<int>("ID_HinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HinhAnh"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("URL_HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_HinhAnh");

                    b.HasIndex("BienSoXe");

                    b.ToTable("hinhAnhXes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.Property<int>("Id_HoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_HoaDon"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ID_DatLich")
                        .HasColumnType("int");

                    b.HasKey("Id_HoaDon");

                    b.HasIndex("ID_DatLich", "Email", "BienSoXe");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LoaiXe", b =>
                {
                    b.Property<int>("ID_LoaiXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_LoaiXe"));

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Name_LoaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_LoaiXe");

                    b.ToTable("loaiXes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id_Quyen")
                        .HasColumnType("int");

                    b.Property<int>("Id_ChucVu")
                        .HasColumnType("int");

                    b.HasKey("Id_Quyen", "Id_ChucVu");

                    b.HasIndex("Id_ChucVu");

                    b.ToTable("phanQuyens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Quyen", b =>
                {
                    b.Property<int>("ID_Quyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Quyen"));

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Name_Quyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Quyen");

                    b.ToTable("quyens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.TaiKhoan", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanCuocCongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GiayPhepLaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("CanCuocCongDan")
                        .IsUnique();

                    b.HasIndex("GiayPhepLaiXe")
                        .IsUnique();

                    b.HasIndex("ID_ChucVu");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Xe", b =>
                {
                    b.Property<string>("BienSoXe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Hide")
                        .HasColumnType("int");

                    b.Property<int>("ID_DiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("ID_HangXe")
                        .HasColumnType("int");

                    b.Property<int>("ID_Loai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("BienSoXe");

                    b.HasIndex("Email1");

                    b.HasIndex("ID_DiaDiem");

                    b.HasIndex("ID_HangXe");

                    b.HasIndex("ID_Loai");

                    b.ToTable("xes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DatLichThueXe", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Xe", "Xe")
                        .WithMany("datLichThueXes")
                        .HasForeignKey("BienSoXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.TaiKhoan", "taiKhoan")
                        .WithMany("datLichThueXes")
                        .HasForeignKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");

                    b.Navigation("taiKhoan");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HinhAnhXe", b =>
                {
                    b.HasOne("DoAnCoSo.Models.Xe", "xe")
                        .WithMany("hinhAnhXes")
                        .HasForeignKey("BienSoXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("xe");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnCoSo.Models.DatLichThueXe", "DatLichThue")
                        .WithMany()
                        .HasForeignKey("ID_DatLich", "Email", "BienSoXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatLichThue");
                });

            modelBuilder.Entity("DoAnCoSo.Models.PhanQuyen", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ChucVu", "ChucVu")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("Id_ChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.Quyen", "Quyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("Id_Quyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("DoAnCoSo.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAnCoSo.Models.ChucVu", "ChucVu")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("ID_ChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Xe", b =>
                {
                    b.HasOne("DoAnCoSo.Models.TaiKhoan", "email")
                        .WithMany("xes")
                        .HasForeignKey("Email1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.DiaDiem", "diaDiems")
                        .WithMany("xes")
                        .HasForeignKey("ID_DiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.HangXe", "hangs")
                        .WithMany("xes")
                        .HasForeignKey("ID_HangXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo.Models.LoaiXe", "loais")
                        .WithMany("xes")
                        .HasForeignKey("ID_Loai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("diaDiems");

                    b.Navigation("email");

                    b.Navigation("hangs");

                    b.Navigation("loais");
                });

            modelBuilder.Entity("DoAnCoSo.Models.ChucVu", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAnCoSo.Models.DiaDiem", b =>
                {
                    b.Navigation("xes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.HangXe", b =>
                {
                    b.Navigation("xes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.LoaiXe", b =>
                {
                    b.Navigation("xes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Quyen", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("DoAnCoSo.Models.TaiKhoan", b =>
                {
                    b.Navigation("datLichThueXes");

                    b.Navigation("xes");
                });

            modelBuilder.Entity("DoAnCoSo.Models.Xe", b =>
                {
                    b.Navigation("datLichThueXes");

                    b.Navigation("hinhAnhXes");
                });
#pragma warning restore 612, 618
        }
    }
}
